### ISSUE TITLE
handleAiTurns 함수 이상 현상

### ISSUE THREAD

**Issue by ywj3493** [fifteenmania/baskin-client#1]
handleAiTurns 함수 테스트 해본 결과 게임 ai 들이 이미 부른 숫자와 같은 숫자를 부르는 현상이 있었습니다. (플레이어가 30을 불렀는데, ai들도 30을 불러서 게임이 종료가 되지 않음)

ai들이 31을 부르고 게임이 종료되는  변경 해야 할 것 같습니다.

**Comment by fifteenmania** [comment]
lib/gameUtil.ts 의 handleAiTurnOnce 에서 AI가 부른 숫자를 잘못 처리하여 생긴 문제인 것 같습니다. 해당 부분 수정하겠습니다. 공헌에 감사드립니다.

**Comment by fifteenmania** [comment]
pull request #4 로 해당 내용 반영하여 픽스하였습니다. 이슈 종료합니다.
